let basepregunta =[
    {pregunta: "Su vehículo se desvía hacia un lado cuando usted frena. usted debería:",
    ayuda:"pinto la ultima cena",
    correcta: "Consultar con su mecánico lo antes posible",
    incorrecta:["Cambiar los neumáticos de un lado hacia el otro y viceversa",
                "Bombear el pedal al frenar",
                "Usar su freno de mano"],
    },
    {pregunta: "Su vehículo se desvía hacia un lado cuando usted frena.¿Cuál es la falla más probable?",
    ayuda:"always",
    correcta: "Frenos mal ajustados",
    incorrecta:["Un bajo nivel del líquido de frenos",
                "Su freno de mano está todavía puesto",
                "Neumáticos con presión de aire inadecuada"],
    },
    {pregunta: "Mientras conduce usted siente un fuerte olor a gasolina.¿Qué debería hacer usted?",
    ayuda:"always",
    correcta: "Detenerse e investigar el problema",
    incorrecta:["No preocuparse, ya que sólo son los gases de escape",
                "Continuar a una velocidad reducida",
                "Continuar porque sabe que se detendrá algunos kilómetros más allá"],
    },

];